[context.production.environment]
  HUGO_VERSION = "0.55.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
HUGO_VERSION = "0.55.2"
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"

[context.branch-deploy]
HUGO_VERSION = "0.55.2"
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"